### ISSUE TITLE
Add to CTAN

### ISSUE THREAD

**Issue by koppor** [adbrucker/llncsconf#1]
I think, it would be great if users could just use this package without having to download it from this page. I'd also like to include this package in my [improved start for LNCS papers](https://latextemplates.github.io/LNCS/). 

Therefore, would it be possible to publish this package on CTAN?

I would propose:

- Add a CHANGELOG.md following [keepachangelog](http://keepachangelog.com/en/1.0.0/) (this is #4)
- Follow semantic versioning and release version 1.0.0 as first version
- Use [ctanify](https://ctan.org/pkg/ctanify) for CTAN preparation

Link to CTAN package upload: https://www.ctan.org/upload

I successfully published [scientific-thesis-cover 4.0.0](https://github.com/latextemplates/scientific-thesis-cover/releases/tag/4.0.0) a few days ago on CTAN and can say that it is very easy with ctanify.

**Comment by adbrucker** [comment]
Hi,
Thanks for the hint - up to now, I considered the style to small to be worthwhile to package ;-). I will upload it do CTAN during the next days (worst case, end of next week, as I am pretty busy at the moment) and close the issue after the upload. 

Best
Achim

**Comment by koppor** [comment]
For the creation of a CTAN archive, the `--notds` option should be given to create a more simpler ZIP (which CTAN likes for simple package). Background: I had this discussion when uploading [scientific-thesis-cover](https://latextemplates.github.io/scientific-thesis-cover/).

**Comment by koppor** [comment]
The CTAN link will be https://ctan.org/pkg/llncsconf and the deep link to the documentation http://texdoc.net/pkg/llncsconf. I just have to be patient. Nevertheless closing this to have 0 open issues.
