### ISSUE TITLE
Wrong margins if a4paper is used

### ISSUE THREAD

**Issue by koppor** [adbrucker/llncsconf#10]
When using following documentclass settings, the paper margins are put wrong when using llncsconf

    \documentclass[norunningheads,a4paper]{llncs}[2015/06/24]

Example output:

![grafik](https://user-images.githubusercontent.com/1366654/37196868-c15a366e-2378-11e8-8b3e-2525455cbd83.png)

**Comment by koppor** [comment]
Does this ref https://github.com/adbrucker/authorarchive/pull/9 somehow?

**Comment by adbrucker** [comment]
Pretty sure this is related to  [adbrucker/authorarchive#9](https://github.com/adbrucker/authorarchive/pull/9), i.e., similar/same fix should apply. I will  look into it during the next days.
