### ISSUE TITLE
Wrong font size of author

### ISSUE THREAD

**Issue by koppor** [adbrucker/llncsconf#15]
The author name "feels" too large in the lower part in the case of `submitted`:

![grafik](https://user-images.githubusercontent.com/1366654/157564246-717fc305-219f-4983-bc5e-db03958538ab.png)

It should have the same size as the line before.

**Comment by adbrucker** [comment]
Well spotted. The LNCS class overwrites the definition of \author using an explicit font size. Luckily, a pristine copy of the author information is stored in \toc@uthor. Thus, using \toc@uthor instead of \@author seems to fix the problem.
