### ISSUE TITLE
`intended` should lead to have the note on each page

### ISSUE THREAD

**Issue by koppor** [adbrucker/llncsconf#16]
In case of `submitted`, the note is on each page:

![grafik](https://user-images.githubusercontent.com/1366654/157564375-732b9647-fd2c-41f7-a580-f56165e531a0.png)

In case of `intended`, the note is only on the first page:

![grafik](https://user-images.githubusercontent.com/1366654/157564443-6e384bc7-dcb8-429a-9e46-e1bbf8a40b1d.png)

I wish, it was on each page, because the "no distribution" hint is extremely important.

I would also add the copyright statement as in `submitted`, because in both cases the authors have the copyright.

(Maybe, it would be possible to configure the content of the copyright - or just a switch to NOT show the copyright at all)

**Comment by adbrucker** [comment]
Fixed by 497181cdf363af6f781f19e3296c5a4adafce5c9.
